### ISSUE TITLE
Locally hosting Stamen Watercolor Maptiles (basemap) Tiles To Run it Offline

### ISSUE THREAD

**Issue by Tselhacode** [stamen/watercolor#5]
I am wondering if I understood correctly from the README part of this repository that following the instructions will allow me to download the stamen watercolor map tiles (I don't require a lot of details like names of countries or cities or borders - basically no human influence). I am working on a project that requires running offline therefore I plan on locally hosting the tiles of zoom level 0 - 10. I am referring to this repository at the link: https://github.com/stamen/watercolor/tree/watercolor-2013

Your clarification will be very much appreciated! Thank You!

**Comment by ebrelsford** [comment]
Where in the readme does it say tha tyou would be able to download the tiles? The readme describes the data that needs to be downloaded in order for tiles to be generated.

**Comment by Tselhacode** [comment]
@ebrelsford Hello Eric, Thank you so much for your reply! I probably didn't word my question correctly. What I wanted to ask was if I downloaded all the software and data dependencies and then follow as per READMe pages on Mapnik and tilestache directories, I will be able to generate tiles of the watercolor so that I can locally host them on my machine and build an interactive map offline. Since this is from 2013, I wasn't sure if this still was working. Have you personally generated tiles from this repository? Do you know of any repository that already has generated watercolor map tiles? Any advice would be much appreciated!

**Comment by ebrelsford** [comment]
In theory you could generate the tiles on your own but it would be a lot of work and I don't think it has been attempted in a long time.

In [our FAQ around the changes to tile hosting from 2023](https://maps.stamen.com/stadia-partnership/), we include directions for getting access to old tiles (including the watercolor tiles) from the S3 buckets they're stored in. This requires having your own AWS account with billing information since the buckets are set up to be requester pays (so Stamen doesn't get charged for your downloads). If you decide to go this route, please test a few tile requests first to ensure that you have the correct setup.

Hope that helps, going to close this issue for now.
